### ISSUE TITLE
Can this work from a .trx file?

### ISSUE THREAD

**Issue by paulvanbladel** [appccelerate/xBehaveMarkdownReport#3]
Trying this library the resulting md file is empty.
Using .net core and run from command line:
´´´
dotnet test -l trx
```
which generates in TestResults folder a .trx file but which is basically an xml file.
When running afterwards xBehaveMarkdownReport it's empty.
Any idea?
Thanks a lot.

**Comment by ursenzler** [comment]
I don't even know what a .trx file is :-O

I only ever used it on full framework together with the xunit console runner.

The report generator probably can't parse the file. it looks for patterns like the test name and it's containing class.

**Comment by paulvanbladel** [comment]
Hi,
Thanks for the prompt feedback.
See also:
https://github.com/xbehave/xbehave.net/issues/483

**Comment by Jazzman82** [comment]
Hi,

I just did some digging to achive something similar like @paulvanbladel is describing in 
xbehave/xbehave.net#483.
I think it basically works for xml-reports generated by .NET-Full console-runner like this:

> xunit.console.exe MyFullFxTestassemblyWithXBehaveScenario.dll -xml testresults.xml

Unfortunately the -xml - Switch doesn't exist for .NET Core's dotnet test command. So I looked into this project: [https://github.com/spekt/xunit.testlogger](url) and was able to do a small adjustment to write out the missing information from xbehave to the xml.

I will probably do a PR on this in the xunit.testlogger-project in the next few days. For now you can try it out when you change the XunitXmlTestLogger-Class to pass **result.DisplayName** to the TestResultInfo-Constructor in the TestResultHandler-Method instead of **result.TestCase.DisplayName**.

This way the generated xml by the following command contains the necessary information for the xBehaveMarkdownReport to work as expected:

> dotnet test MyCoreFxTestassemblyWithXBehaveScenario.dll --logger:"xunit;LogFilePath=testresults.xml"

**Comment by ursenzler** [comment]
@paulvanbladel @Jazzman82 I wrote a new report generator that can directly generate a report from a .trx file, including some other improvements. You can find it here: https://github.com/ursenzler/xBehaveReportGenerator
